dist: xenial
language: python
cache: pip
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "pypy2.7-6.0"
 - "pypy3.5-6.0"

notifications:
  email: false
addons:
  apt:
    packages:
    - git
    - golang
before_install:
 - export GOPATH=~/go
 - go get github.com/BurntSushi/toml-test
 - git clone https://github.com/BurntSushi/toml-test
install:
 - pip install tox-travis
 - python setup.py install
 - chmod +x ./tests/*.sh
script:
 - ~/go/bin/toml-test ./tests/decoding_test.sh
 - tox
 - tox -e check
after_success:
 - tox -e codecov
